name: Review Vulnerability Due Dates
on:
  workflow_dispatch
jobs:
  Ubuntu:
    name: Add deadline labels to issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: phenggeler/github-issue-due-dates-action@v2.3
        with:
          GH_TOKEN: "${{ secrets.GH_SECRET }}"
